version: '3.8'

services:
  api:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - smtp
    volumes:
      - delivery-app:/db.sqlite3

  smtp:
    image: rnwood/smtp4dev
    ports:
      - '25:25'
      - '5000:80'

volumes:
   delivery-app: