version: '3.8'

services:
  api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - delivery-app:/data

  smtp:
    image: rnwood/smtp4dev
    ports:
      - '5000:80'
      - '25:25'

volumes:
   delivery-app: