# Generated by Django 4.2.7 on 2023-12-04 14:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enduser', '0002_remove_customuser_email_verification_sent_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='confirmation_attempts',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp',
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired', models.DateTimeField(default=datetime.datetime(2023, 12, 4, 14, 36, 22, 865175, tzinfo=datetime.timezone.utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
