# Generated by Django 4.2.7 on 2023-12-05 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enduser', '0003_remove_customuser_confirmation_attempts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='user',
        ),
        migrations.AddField(
            model_name='pin',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pin',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pin',
            name='expired',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 5, 12, 35, 34, 292795, tzinfo=datetime.timezone.utc)),
        ),
    ]
