# Generated by Django 4.2.7 on 2023-12-19 23:24

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enduser', '0005_profile_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='email',
            field=models.EmailField(max_length=50, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='pin',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 19, 23, 34, 53, 456849, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
