# Generated by Django 4.2.7 on 2023-12-20 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enduser', '0008_alter_customuser_email_alter_pin_otp_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 20, 8, 35, 51, 517052, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
