# Generated by Django 4.2.7 on 2023-12-21 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enduser', '0009_alter_pin_otp_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pin',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 21, 7, 12, 2, 538655, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
