# Generated by Django 4.2.7 on 2023-12-21 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enduser', '0010_alter_pin_email_alter_pin_otp_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 21, 11, 48, 41, 644475, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
