# Generated by Django 4.2.7 on 2023-12-21 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enduser', '0011_alter_pin_otp_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='max_otp_try',
            field=models.PositiveSmallIntegerField(default=3, max_length=2),
        ),
        migrations.AlterField(
            model_name='pin',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 21, 12, 54, 11, 705288, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
