# Generated by Django 4.2.7 on 2023-12-22 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enduser', '0012_alter_pin_max_otp_try_alter_pin_otp_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pin',
            name='max_otp_try',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='pin',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 22, 20, 25, 36, 593251, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
