# Generated by Django 4.2.7 on 2023-12-24 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enduser', '0013_alter_customuser_is_active_alter_pin_max_otp_try_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 24, 22, 11, 37, 474015, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
