# Generated by Django 4.2.7 on 2023-12-24 22:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enduser', '0014_alter_pin_otp_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pin',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 24, 22, 13, 56, 949356, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
