# Generated by Django 4.2.7 on 2023-12-27 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enduser', '0018_customuser_is_verified_alter_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 27, 12, 19, 43, 269975, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
