# Generated by Django 4.2.7 on 2023-12-27 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enduser', '0020_profile_id_alter_pin_otp_expiry_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 27, 16, 18, 23, 583127, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
